# Generated by Django 2.2.3 on 2022-09-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_register', '0002_playerteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerteam',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='player_register.Player'),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='player_register.Team'),
        ),
    ]
