# Generated by Django 2.2.3 on 2022-09-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_register', '0004_auto_20220919_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
        migrations.AddField(
            model_name='team',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player_register.Player'),
        ),
    ]
